    <script src="<?php echo BASE_URL; ?>assets/js/jquery-1.10.2.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/classie.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/cbpAnimatedHeader.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/freelancer.js"></script>

</body>

</html>
