<div class="row">
  <div class="large-3 columns">
    <h1>
      <a href="<?php echo BASE_URL; ?>">
        <img src="http://placehold.it/400x100&text=Logo">
      </a>
    </h1>
    </div>
    <div class="large-9 columns">
      <ul class="button-group right">
        <li><a href="<?php echo BASE_URL; ?>" class="button">Home</a></li>
        <li><a href="<?php echo BASE_URL; ?>products" class="button">Products</a></li>
        <li><a href="<?php echo BASE_URL; ?>welcome/about" class="button">About</a></li>
        <li><a href="<?php echo BASE_URL; ?>contact" class="button">Contact</a></li>
      </ul>
  </div>
</div>
