<div class="large-6 columns">
  <ul class="inline-list right">
        <li><a href="<?php echo BASE_URL; ?>"><?php echo $geonav["home"]; ?></a></li>
        <li><a href="<?php echo BASE_URL; ?>products"><?php echo $geonav["products"]; ?></a></li>
        <li><a href="<?php echo BASE_URL; ?>welcome/about"><?php echo $geonav["about"]; ?></a></li>
        <li><a href="<?php echo BASE_URL; ?>contact"><?php echo $geonav["contact"]; ?></a></li>
  </ul>
</div>
