<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive round" src="<?php echo $geoheader["logo_large"]; ?>" alt="">
                <div class="intro-text">
                    <span class="name"><?php echo $geoheader["cta_title_1"]; ?></span>
                    <hr class="star-light">
                    <span class="skills"><?php echo $geoheader["cta_sub_1"]; ?></span>
                </div>
            </div>
        </div>
    </div>
</header>
