<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive" src="<?php echo BASE_URL; ?>assets/img/profile.png" alt="">
                <div class="intro-text">
                    <span class="name">Boogie Board It!</span>
                    <hr class="star-light">
                    <span class="skills">Where you buy authentic, pure fun!</span>
                </div>
            </div>
        </div>
    </div>
</header>
