<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive round" src="http://placehold.it/256x256&text=logo" alt="">
                <div class="intro-text">
                    <span class="name">Boogie Board It!</span>
                    <hr class="star-light">
                    <span class="skills">Where you buy fun!</span>
                </div>
            </div>
        </div>
    </div>
</header>
