<!-- Portfolio Modals -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_1']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_1']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_1']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_2']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_2']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_2']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_3']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_3']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_3']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_4']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_4']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_4']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_5']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_5']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_5']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2><?php echo $geoproducts['product_title_6']; ?></h2>
                        <hr class="star-primary">
                        <img src="<?php echo $geoproducts['product_large_image_6']; ?>" class="img-responsive img-centered" alt="">
                        <p>
                          <?php echo $geoproducts['product_intro_6']; ?>
                        </p>
                        <ul class="list-inline item-details">
                            <li><strong><a href="#">Buy</a></strong>
                            </li>
                            <li><strong><a href="#">Reviews</a></strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
